### ISSUE TITLE
Any example script available for multiple permissions with the reason of permission?

### ISSUE THREAD

**Issue by midopooler** [yasirkula/UnityAndroidRuntimePermissions#10]
Actually I want to take 4 permissions in one go.
The following are the permissions
1. audio
2. external storage
3. record video
4. exposing sensitive information during recording

I tried it using `Permission[] RequestPermissions( params string[] permissions )` but didn't get how exactly use it, I even tried to go through the unity forum of this repo and the closed issues as well, but didn't get any help.

@yasirkula Please help?

**Comment by yasirkula** [comment]
Hope this helps:

```csharp
// These permissions must be declared in AndroidManifest.xml file
string storage = "android.permission.WRITE_EXTERNAL_STORAGE";
string audio = ...;
string video = ...;
string sensitiveInfo = ...;

// Request all permissions at once
AndroidRuntimePermissions.Permission[] result = AndroidRuntimePermissions.RequestPermissions( storage, audio, video, sensitiveInfo );

// Check if all permissions are granted
Debug.Log( "All permissions granted: " + System.Array.TrueForAll( result, ( permission ) => permission == AndroidRuntimePermissions.Permission.Granted ) );
```

**Comment by midopooler** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<manifest 
  xmlns:android="http://schemas.android.com/apk/res/android" package="com.setik.androidutils">
  <application android:icon="@drawable/app_icon" android:label="@string/app_name">
    <activity android:name="com.setik.kampertee.AndroidUtils" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    <meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="true" />
  </application>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
</manifest>

```
Above is my exact AndroidManifest.xml. Where exactly to declare the permissions in this script. I know it may sound a bit frustrating for you, but I'm a noob when it comes to XML. @yasirkula Please help. 🙏

**Comment by yasirkula** [comment]
You just duplicate the uses-permission line for each permission.

**Comment by midopooler** [comment]
Sorry, I forgot to thank you for this repo and quick responses on this repository. 
Also, I'm hereby giving you 5 star rating on the asset store.

**Comment by yasirkula** [comment]
Thank you, I appreciate it 😃

**Comment by midopooler** [comment]
Hi @yasirkula ,  I am asking for 4 permissions at the very start of the app. That has been done. 
But I don't want user to move forward if any of the permission is denied. 
For that I used `AndroidRuntimePermissions.Permission result3 = AndroidRuntimePermissions.CheckPermission(storage);`
and keep doing it for every permission (I guess array wasn't working for that, but leave it that's not a concern)

Now my question is how do I debug this info in my unity simulator that the permission is denied or granted?
If not my unity simulator, even if I'm doing this in my android phone, still how can I debug information?

**Comment by yasirkula** [comment]
Permissions will always return Granted in Unity editor. On an actual device, you can Debug.Log the permission result(s) and see those logs via "adb logcat", Unity's "Android Logcat" package or an [in-game debug console](https://github.com/yasirkula/UnityIngameDebugConsole) like this.

**Comment by midopooler** [comment]
Thanks, It helped me!!

**Comment by yasirkula** [comment]
Happy to help 😺
