### ISSUE TITLE
Version mistmatched

### ISSUE THREAD

**Issue by favoyang** [yasirkula/UnityAndroidRuntimePermissions#11]
**Description of the bug**

Git tag 1.1.4
[package.json](https://github.com/yasirkula/UnityAndroidRuntimePermissions/blob/32c354a49cd9b329a1ccba4870046d20ac1136dd/package.json
) 1.1.3
package.json@master: 1.1.4

**How to fix it?**
Re-tag 1.1.4 from the master branch.

**Comment by yasirkula** [comment]
Fixed it now, thanks.
