### ISSUE TITLE
Native call in OnApplicationPause causes crash

### ISSUE THREAD

**Issue by AntiGuide** [yasirkula/UnityAndroidRuntimePermissions#2]
The third party plugin UniWebView I use executes a JavaAndroidClass.CallStatic in the OnApplicationPause event which lets the app crash. I don't know whether the fault is on this plugins end or on theirs, but this didn't happen in previous versions.

Could you maybe check if this is specific to this native call of just any native call in OnApplicationPause?

We love to use your plugin! Thanks for the good work :relaxed:

**Comment by yasirkula** [comment]
Thank you! By previous versions, do you mean this plugin's previous versions or UniWebView's previous versions? This plugin shouldn't interfere with OnApplicationPause, as far as I know.

Could you maybe try creating a new project, importing only this plugin and calling the RequestPermission function in OnApplicationPause to see if it crashes?

**Comment by AntiGuide** [comment]
I was refering to your plugin before the 1.1 update aka the Unity 2019 patch. 

I'll try to find time to do so.

**Comment by yasirkula** [comment]
I've created a new project in Unity 2019.1.8f1, attached the following script to an object in my scene and added the permissions to my AndroidManifest.xml. The permission dialog showed up and then the app continued as usual. I've also minimized the app and then restored it and there were still no crashes.

Can you also test this script in a new Unity project and see if everything works smoothly for you, as well?

```csharp
using UnityEngine;

public class TestScript : MonoBehaviour
{
	Transform cam;
	void Start()
	{
		cam = Camera.main.transform;
		Invoke( "Test", 2f );
	}

	private void Update()
	{
		cam.Rotate( 0f, Time.deltaTime * 90f, 0f );
	}

	private void OnApplicationPause( bool pause )
	{
		AndroidJavaClass c = new AndroidJavaClass( "android.os.Environment" );
		Debug.Log( c.CallStatic<string>( "getExternalStorageState" ) );
	}

	private void Test()
	{
		var results = AndroidRuntimePermissions.RequestPermissions( "android.permission.READ_PHONE_STATE", "android.permission.READ_CONTACTS" );
	}
}
```

**Comment by AntiGuide** [comment]
Cool thank you for putting the effort in. Sadly I won't be able to test this for the next 3 weeks. I'll try this when I get back to work.
