### ISSUE TITLE
not work at all

### ISSUE THREAD

**Issue by MarcoLavoro** [yasirkula/UnityAndroidRuntimePermissions#4]
i imported the assets, and write this at start:

    AndroidRuntimePermissions.Permission result = AndroidRuntimePermissions.RequestPermission("android.permission.WRITE_EXTERNAL_STORAGE");
        if (result == AndroidRuntimePermissions.Permission.Granted)
            Debug.Log("We have permission to access external storage!");
        else
            Debug.Log("Permission state: " + result);

the only thing android reply me is this:
AndroidPlayer(ADB@127.0.0.1:34999)</i> Permission state: Denied

but it not ask me ANYTHING, and i can not set the permiossion in app settings because it not show in the app settings

**Comment by yasirkula** [comment]
Does the "android.permission.WRITE_EXTERNAL_STORAGE" permission exist in UNITY_PROJECT_PATH/Temp/StagingArea/AndroidManifest.xml after building your project? If not, you need to set "Write Permission" to "External (SDCard)" in Player Settings.

**Comment by kjyv** [comment]
Using 2019.3.7f, I also don't get any popups, using Permissions.Camera and Permissinos.FineLocation  though. The app does show popups when using Permission.RequestUserPermission(Permission.Camera) - but that's not blocking and I have no way to know if user ticked "don't ask again"... But then UnityManifest is not be the reason, it contains both permissions.

**Comment by yasirkula** [comment]
Permission.RequestUserPermission is Unity's API, you need to use AndroidRuntimePermissions.RequestPermission if you are using my AndroidRuntimePermissions plugin.

**Comment by kjyv** [comment]
Sorry, my sentence was a bit short. I meant I don't get any popups using your plugin when calling AndroidRuntimePermissions.RequestPermission, I do get popups using the Unity API though as an indicator that there are no manifest issues.

**Comment by yasirkula** [comment]
I see, thanks for the clarification. Can you see any meaningful error messages in logcat? If you are using ProGuard minification, can you try adding the following line to its filters:

`-keep class com.yasirkula.unity.* { *; }`

**Comment by antoniohof** [comment]
I'm getting this too only with the MICROPHONE permission

**Comment by yasirkula** [comment]
Does the MICROPHONE permission exist in UNITY_PROJECT_PATH/Temp/StagingArea/AndroidManifest.xml after building your project? If not, you need to add the permission to your project's AndroidManifest.xml.

**Comment by kjyv** [comment]
I haven't had the time to test it again (I went with a Unity only solution so far) but noticed it didn't get built with ProGuard, so that probably wasn't the reason.

**Comment by yasirkula** [comment]
There is a small chance that Unity adds the Camera permission to AndroidManifest automatically if you use Permissions.Camera. My plugin doesn't have this functionality, you must explicity declare the needed permissions in AndroidManifest.xml.

**Comment by mcolombo** [comment]
Hi,
Im trying to get these 3 permissions:
"android.permission.READ_PHONE_STATE", "android.permission.READ_SMS", "android.permission.READ_CONTACTS"

But no popup appears.
I tried declaring them in the manifest, but didnt work.

Am i missing something here?
Thanks!

**Comment by yasirkula** [comment]
Are there any error messages that show up in logcat when asking permissions?

**Comment by mcolombo** [comment]
> Are there any error messages that show up in logcat when asking permissions?

No, nothing.
I used Unity API and worked.
UnityEngine.Android.Permission.RequestUserPermission("android.permission.READ_CONTACTS");

**Comment by yasirkula** [comment]
If you print the permission with Debug.Log, does it say Denied? On which device(s) did you have this issue?

**Comment by mcolombo** [comment]
> If you print the permission with Debug.Log, does it say Denied? On which device(s) did you have this issue?

Hey, thanks for the reply.
I already uninstalled the plugin since the unity api is working.

Thanks for your help anyway.

**Comment by yasirkula** [comment]
P.S. Apparently the microphone permission is named `android.permission.RECORD_AUDIO` and not `android.permission.MICROPHONE`.

**Comment by MarcoLavoro** [comment]
sorry for the late reply.
I still get NO MESSAGE from this

	AndroidRuntimePermissions.Permission[] result = AndroidRuntimePermissions.RequestPermissions( "android.permission.WRITE_EXTERNAL_STORAGE", "android.permission.CAMERA" );
			if( result[0] == AndroidRuntimePermissions.Permission.Granted && result[1] == AndroidRuntimePermissions.Permission.Granted )
				Debug.Log( "We have all the permissions!" );
			else
				Debug.Log( "Some permission(s) are not granted..." );
				


"Write Permission" to "External (SDCard)" in Player Settings. is setted

**Comment by yasirkula** [comment]
@MarcoLavoro Did you declare `<uses-permission android:name="android.permission.CAMERA" />` permission in your AndroidManifest.xml?

**Comment by MarcoLavoro** [comment]
> @MarcoLavoro Did you declare `<uses-permission android:name="android.permission.CAMERA" />` permission in your AndroidManifest.xml?

Seems that the main manifes was rewrited, so the point is that I have also to modyfy the manifest.
Ok thanks for me this is closed and work fine

**Comment by MarcoLavoro** [comment]
solved adding the permission also in the manifest
