### ISSUE TITLE
CheckPermission(permission) is never "Permission.Denied" even if choosing "Never ask again"

### ISSUE THREAD

**Issue by diegoleao** [yasirkula/UnityAndroidRuntimePermissions#5]
This "if" is never entered:

if (AndroidRuntimePermissions.CheckPermission(permission) == AndroidRuntimePermissions.Permission.Denied)

Even when I choose "Never ask again". I'm only using this part of androidruntimepermissions (to actually request the permission, I use Unity's api).

Am I doing something wrong, do I need to "prepare" something before comparing checkpermission to denied?

Thank you

**Comment by yasirkula** [comment]
You'll have to request the permission with this plugin, as well; that's because RequestPermission is the function that determines whether or not "Never ask again" is clicked and it can't fetch that information from Unity's API.

**Comment by diegoleao** [comment]
I see! Thank you for the quick answer :)
