### ISSUE TITLE
Add support for iOS Permissions or new Repo for Project that supports both Android and iOS

### ISSUE THREAD

**Issue by i9hdkill** [yasirkula/UnityAndroidRuntimePermissions#6]
Hey,
this project works well for Android, but we are developing for both platforms and would like to use the same lib for both android and ios.

Having this resource(or a new repo) support Android and iOS would be awesome. That way it's easier to query permissions cross platform. (I saw some of the required code already in UnityNativeCamera)

Cheers, John

**Comment by yasirkula** [comment]
Unlike Android, each permission in iOS is handled in a different way and some require a separate framework, e.g. camera permission requires Photos framework (or AssetsLibrary framework on older iOS versions). I don't think a user who is only interested in e.g. location permission would want to bloat their project with numerous additional frameworks.

Thank you for the feedback but I'm not planning to add iOS support.

**Comment by i9hdkill** [comment]
Thanks, did some research aswell and came to the same conclusion. Thanks for responding so quickly
