### ISSUE TITLE
Not work with gradle or firebase?

### ISSUE THREAD

**Issue by mostafanastary** [yasirkula/UnityAndroidRuntimePermissions#7]
Hi, Thank you for the plugin.
I'm using it for a while, but after using firebase, I should change some settings like build system to Gradle and Target API Level to Android 9.0 'Pie' for androidX . 

![image](https://user-images.githubusercontent.com/19608063/87221729-818f3680-c383-11ea-9776-7801cd4a9711.png)

After all my application after running show me some error in SDK's Monitor :

![image](https://user-images.githubusercontent.com/19608063/87221689-3412c980-c383-11ea-8fff-e2cad2e9fc16.png)

ps: I upgrade the plugin to last.

**Comment by yasirkula** [comment]
It says that the plugin's native source code is stripped from the build. If your project uses ProGuard, try adding the following line to ProGuard filters: `-keep class com.yasirkula.unity.* { *; }`

**Comment by mostafanastary** [comment]
No, I don't use ProGuard , but gradle . Is there any way to solve it ?

**Comment by yasirkula** [comment]
The code minification that was somehow introduced by Firebase should either exclude [these classes](https://github.com/yasirkula/UnityAndroidRuntimePermissions/tree/master/.github/JAR%20Source) or be turned off. I haven't used Firebase myself so I don't know how it enables code minification out of nowhere.

**Comment by yasirkula** [comment]
Fixed in https://github.com/yasirkula/UnityAndroidRuntimePermissions/commit/2b7932e19687d5b5f2aa5e0a5bace60a6a601f91
