### ISSUE TITLE
Works for camera and external storage write, but not microphone

### ISSUE THREAD

**Issue by ksyao2002** [yasirkula/UnityAndroidRuntimePermissions#8]
Attached is what I call:

AndroidRuntimePermissions.Permission result1 = AndroidRuntimePermissions.RequestPermission("android.permission.CAMERA");
        AndroidRuntimePermissions.Permission result2 = AndroidRuntimePermissions.RequestPermission("android.permission.MICROPHONE");
        AndroidRuntimePermissions.Permission result3 = AndroidRuntimePermissions.RequestPermission("android.permission.WRITE_EXTERNAL_STORAGE");

Here is my manifest:

\<uses-permission android:name="android.permission.CAMERA" />
	\<uses-permission android:name="android.permission.MICROPHONE" />
	\<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />"

When I run it in build, it doesn't give error messages but it also never asks for the permission. When I print out result2 I get denied.

**Comment by yasirkula** [comment]
Yes, seems like the microphone permission is named `android.permission.RECORD_AUDIO` 😄
